package funks;

public class Function 
{
    public void delay(int time)
    {
        try
        {
            Thread.sleep(time);
        }
        catch (InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }
    }


    public  void print(String data , int time)
    {
        for(int i=0; i<data.length(); i++)
        {
            System.out.print(data.charAt(i));
            delay(time);
        }
        
    }

    public  void drawLine(char ch)
    {
        System.out.println();

        for(int i=0; i<160; i++)
        {
            System.out.print(ch);
            delay(5);
        }
        System.out.println();
        delay(1000);
    }

    public  void space(int num)
    {
        for(int i=0; i<num; i++)
        {
            System.out.print(" ");
        }
    }

    public void introducer()
    {
    
        space(70);
        print("Welcome To The Game",40);
        System.out.println();
        space(70);
        delay(1000);
        print("GUESS THE NUMBER ", 50);
        delay(400);
        print("2", 40);
        delay(500);
        delay(1000);
    
        drawLine('-');
        print("How to play...", 10);System.out.println();
        delay(1000);        
        System.out.println();
        
    
        print(">",10);
        delay(500);
        print(" Game includes Two Turns,", 40);
        delay(300);
        print(" User's Turn", 40);
        delay(300);
        print( " and Machine's Turn.", 40);
        delay(1400);
        System.out.println();
    
        print(">",10);
        delay(500);
        print(" In User's turn,", 40);
        delay(300);
        print(" you have to Guess that Hidden number which is randomly generated by the machine", 40);
        delay(300);
        print(" in given range.", 40);
        delay(1400);
        System.out.println();
    
        print(">",10);
        delay(500);
        print(" In Machine's turn,", 40);
        delay(300);
        print(" you have to consider any random number in your mind in between that range", 40);
        delay(300);
        print(" and have to give the hints to the machine on what it is asking for.", 40);
        delay(1400);
        System.out.println();
    
        print(">",10);
        delay(500);
        print( " By default total 6 turns are there", 40);
        delay(300);
        print( " (3 for each),", 50);
        delay(300);
        print( " 10 guesses for users and 12 for machine, in each turn.", 40);

        delay(1400);
        System.out.println();
    
        print(">",10);
        delay(500);
        print( " You can Quit the game any time by typing ", 40);
        delay(300);
        print("'exit' ", 80);
        delay(300);
        print("during input.", 40);
        delay(1400);
        System.out.println();
        
        System.out.println();
        print("Explore more Features and Fun while playing...! ",40);
        delay(1000);
        print("Best Luck!", 50);
        delay(1000);
        System.out.println();System.out.println(); 
               
        drawLine('-');
    }

} 